### ISSUE TITLE
✨[FEAT] 보관함 사이드바 기능 구현

### ISSUE THREAD

**Issue by Somin-DS** [DeveloperAcademy-POSTECH/MC2-Team8-WorkItTalkIt#11]
## 💡 Issue
보관함 화면의 사이드바 기능을 구현합니다.
![보관함UI](https://user-images.githubusercontent.com/69718283/173538293-b2985c37-ea39-46f7-8f8d-62d82df51bb0.png)

## 📝  todo
- [ ] 폴더 편집버튼 클릭시 -> 삭제,정보 버튼 나타나기
- [ ] 폴더 추가버튼 클릭시 -> 폴더 추가 모달화면 띄우기, 폴더추가 기능 구현
- [ ] Swipe로 삭제 기능구현
- [ ] 삭제시 Alert창 띄우기
