### ISSUE TITLE
✅[ADD] 첫화면, 편집화면 UI 구성하기

### ISSUE THREAD

**Issue by HANS5109** [DeveloperAcademy-POSTECH/MC2-Team8-WorkItTalkIt#17]
## 💡 Issue
첫 화면과 편집화면의 UI를 구성합니다.

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/103012796/173717855-46b1e451-88cc-4a5c-9924-cf2ef7d66733.png">
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/103012796/173717873-5aa603e0-c0a2-4c27-bbbc-da7d7c78695c.png">

## 📝  todo
- [ ] '홈 편집' 아이콘 넣기
- [ ] '+', '보관함', '완료' btn 넣기
- [ ] '보관할 툴 영역' 설정
- [ ] '페이지 컨트롤' UI 넣기
