### ISSUE TITLE
✨[FEAT] Long Press Gesture 구현

### ISSUE THREAD

**Issue by HANS5109** [DeveloperAcademy-POSTECH/MC2-Team8-WorkItTalkIt#18]
## 💡 Issue
Long Press Gesture를 구현합니다

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/103012796/173718377-02a1c659-1f79-4ddd-9a15-be65167bb8e8.png">

## 📝  todo
- [ ] Long Press Gesture 영역 부여
- [ ] Long Press Gesture 영역 활성화
- [ ] Long Press Gesture 영역 기능부여 (edit mode 전환)
