### ISSUE TITLE
✨[FEAT] 편집모드 안에 각 버튼에 기능부여

### ISSUE THREAD

**Issue by HANS5109** [DeveloperAcademy-POSTECH/MC2-Team8-WorkItTalkIt#19]
## 💡 Issue
편집모드 안에 있는 각각의 버튼들에 기능을 부여해 줍니다.

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/103012796/173720176-c1130206-bb05-414d-8395-2cdaa1811c2b.png">

## 📝  todo
- [ ] '완료'btn 눌렀을때 화면 전환 기능구현
- [ ] '+'btn 눌렀을때 화면 전환 기능구현
- [ ] '보관함'btn 눌렀을때 화면 전환 기능구현
