### ISSUE TITLE
[FEAT] 사이드바, 화면 뷰 UI 그리기 

### ISSUE THREAD

**Issue by lenamin** [DeveloperAcademy-POSTECH/MC2-Team8-WorkItTalkIt#3]
## 💡 Issue
new툴 추가 및 보관함 화면을 위한 UI를 그린다. 

## 📝  todo
- [ ] new툴 사이드바 UI 그리기
- [ ] new툴 화면뷰 UI 그리기
- [ ] 보관함 화면뷰 사이드바 UI 그리기
