### ISSUE TITLE
✅[ADD] 새로운 툴 추가 (Modal - New Tool) 기능 구현

### ISSUE THREAD

**Issue by lenamin** [DeveloperAcademy-POSTECH/MC2-Team8-WorkItTalkIt#9]
## 💡 Issue
Modal New Tool 화면의 기능을 구현합니다. 

## 📝  todo
- [ ] `제안` 뷰 : 툴을 누르면 해당 카테고리뷰로 전환되는 기능
- [ ] `카테고리` 뷰 : 각 툴을 선택하면 툴 테두리 활성화되는 기능 
- [ ] `카테고리` 뷰 : 활성화 후 추가버튼 누르면 모달 내려가며 편집모드로 전환되는 기능 
- [ ] `카테고리` 뷰 : 편집모드에서 툴을 추가하는 기능 (드래그 앤 드랍)
